version: '2.4'
services:
    myfirstserver:
        container_name: server
        command: python3 hello.py
        ports:
            - 8000:8000
        build:
            context: .
            dockerfile: Dockerfile    

    grafana:
        container_name: grafana
        ports:
            - 3000:3000
        image: grafana/grafana            

    prometheus:
        container_name: prom
        ports:
            - 9090:9090
        image: prom/prometheus
        volumes: 
            - C:\Users\singhkis\Desktop\Dockerfiles\prometheus.yml:/etc/prometheus/prometheus.yml    